import pwn
import pwnlib
states = {
  "Alabama":"Montgomery",
  "Alaska":"Juneau",
  "Arizona":"Phoenix",
  "Arkansas":"Little Rock",
  "California":"Sacramento",
  "Colorado":"Denver",
  "Connecticut":"Hartford",
  "Delaware":"Dover",
  "Florida":"Tallahassee",
  "Georgia":"Atlanta",
  "Hawaii":"Honolulu",
  "Idaho":"Boise",
  "Illinois":"Springfield",
  "Indiana":"Indianapolis",
  "Iowa":"Des Moines",
  "Kansas":"Topeka",
  "Kentucky":"Frankfort",
  "Louisiana":"Baton Rouge",
  "Maine":"Augusta",
  "Maryland":"Annapolis",
  "Massachusetts":"Boston",
  "Michigan":"Lansing",
  "Minnesota":"St. Paul",
  "Mississippi":"Jackson",
  "Missouri":"Jefferson City",
  "Montana":"Helena",
  "Nebraska":"Lincoln",
  "Nevada":"Carson City",
  "New Hampshire":"Concord",
  "New Jersey":"Trenton",
  "New Mexico":"Santa Fe",
  "New York":"Albany",
  "North Carolina":"Raleigh",
  "North Dakota":"Bismarck",
  "Ohio":"Columbus",
  "Oklahoma":"Oklahoma City",
  "Oregon":"Salem",
  "Pennsylvania":"Harrisburg",
  "Rhode Island":"Providence",
  "South Carolina":"Columbia",
  "South Dakota":"Pierre",
  "Tennessee":"Nashville",
  "Texas":"Austin",
  "Utah":"Salt Lake City",
  "Vermont":"Montpelier",
  "Virginia":"Richmond",
  "Washington":"Olympia",
  "West Virginia":"Charleston",
  "Wisconsin":"Madison",
  "Wyoming":"Cheyenne"}


countries = {
    "Afghanistan":"Kabul",
    "Albania":"Tirana",
    "Algeria":"Algiers",
    "American Samoa":"Fagatogo",
    "Andorra":"Andorra la Vella",
    "Angola":"Luanda",
    "Anguilla":"The Valley",
    "Antigua and Barbuda":"Saint John's",
    "Argentina":"Buenos Aires",
    "Armenia":"Yerevan",
    "Aruba":"Oranjestad",
    "Australia":"Canberra",
    "Austria":"vienna",
    "Azerbaijan":"Baku",
    "Bahamas":"Nassau",
    "Bahrain":"Manama",
    "Bangladesh":"Dhaka",
    "Barbados":"Bridgetown",
    "Belarus":"Minsk",
    "Belgium":"Brussels",
    "Belize":"Belmopan",
    "Benin":"Porto-Novo",
    "Bermuda":"Hamilton",
    "Bhutan":"Thimphu",
    "Bolivia":"La Paz",
    "Bosnia and Herzegovina":"Sarajevo",
    "Botswana":"Gaborone",
    "Brazil":"Brasília",
    "Brunei":"Bandar Seri Begawan",
    "Bulgaria":"Sofia",
    "Burkina Faso":"Ouagadougou",
    "Burundi":"Bujumbura",
    "Cambodia":"Phnom Penh",
    "Cameroon":"Yaound",
    "Canada":"Ottawa",
    "Cape Verde":"Praia",
    "Cayman Islands":"George Town",
    "Central African Republic":"Bangui",
    "Chad":"N'Djamena",
    "Chile":"Santiago de Chile",
    "China":"Peking",
    "Christmas Island":"Flying Fish Cove",
    "Cocos (Keeling) Islands":"West Island",
    "Colombia":"Santaf",
    "Comoros":"Moroni",
    "Republic of the Congo":"Brazzaville",
	"Democratic Republic of the Congo":"Kinshasa",
    "Cook Islands":"Avarua",
    "Costa Rica":"San Jos",
    "Croatia":"Zagreb",
    "Cuba":"La Habana",
    "Cyprus":"Nicosia",
    "Czech Republic":"Prague",
    "Denmark":"Copenhagen",
    "Djibouti":"Djibouti",
    "Dominica":"Roseau",
    "Dominican Republic":"Santo Domingo",
    "East Timor (Timor-Leste)":"Dili",
    "Ecuador":"Quito",
    "Egypt":"Cairo",
    "El Salvador":"San Salvador",
    "England":"London",
    "Equatorial Guinea":"Malabo",
    "Eritrea":"Asmara",
    "Estonia":"Tallinn",
    "Ethiopia":"Addis Ababa",
    "Falkland Islands":"Stanley",
    "Faroe Islands":"Tórshavn",
    "Fiji":"Suva",
    "Finland":"Helsinki",
    "France":"Paris",
    "French Guiana":"Cayenne",
    "French Polynesia":"Papeete",
    "Gabon":"Libreville",
    "Gambia":"Banjul",
    "Georgia":"Tbilisi",
    "Germany":"Berlin",
    "Ghana":"Accra",
    "Gibraltar":"Gibraltar",
    "Greece":"Athens",
    "Greenland":"Nuuk",
    "Grenada":"Saint George's",
    "Guadeloupe":"Basse Terre",
    "Guam":"Aga",
    "Guatemala":"Guatemala City",
    "Guinea":"Conakry",
    "Guinea-Bissau":"Bissau",
    "Guyana":"Georgetown",
    "Haiti":"Port-au-Prince",
    "Vatican City":"Citt",
    "Honduras":"Tegucigalpa",
    "Hong Kong":"Victoria",
    "Hungary":"Budapest",
    "Iceland":"Reykjav",
    "India":"New Delhi",
    "Indonesia":"Jakarta",
    "Iran":"Tehran",
    "Iraq":"Baghdad",
    "Ireland":"Dublin",
    "Israel":"Jerusalem",
    "Italy":"Rome",
    "Ivory Coast":"Yamoussoukro",
    "Jamaica":"Kingston",
    "Japan":"Tokyo",
    "Jordan":"Amman",
    "Kazakhstan":"Astana",
    "Kenya":"Nairobi",
    "Kiribati":"Tarawa",
    "Kuwait":"Kuwait City",
    "Kyrgyzstan":"Bishkek",
    "Laos":"Vientiane",
    "Latvia":"Riga",
    "Lebanon":"Beirut",
    "Lesotho":"Maseru",
    "Liberia":"Monrovia",
    "Libya":"Tripoli",
    "Liechtenstein":"Vaduz",
    "Lithuania":"Vilnius",
    "Luxembourg":"Luxembourg",
    "Macao":"Macao",
    "Macedonia":"Skopje",
    "Madagascar":"Antananarivo",
    "Malawi":"Lilongwe",
    "Malaysia":"Kuala Lumpur",
    "Maldives":"Male",
    "Mali":"Bamako",
    "Malta":"Valletta",
    "Marshall Islands":"Majuro",
    "Martinique":"Fort-de-France",
    "Mauritania":"Nouakchott",
    "Mauritius":"Port Louis",
    "Mayotte":"Mamoutzou",
    "Mexico":"Mexico City",
    "Federated States of Micronesia":"Palikir",
    "Moldova":"Chisinau",
    "Monaco":"Monaco-Ville",
    "Mongolia":"Ulan Bator",
    "Montserrat":"Plymouth",
    "Morocco":"Rabat",
    "Mozambique":"Maputo",
    "Myanmar":"Rangoon (Yangon)",
    "Namibia":"Windhoek",
    "Nauru":"Yaren",
    "Nepal":"Kathmandu",
    "Netherlands":"Amsterdam",
    "Netherlands Antilles":"Willemstad",
    "New Caledonia":"Noum",
    "New Zealand":"Wellington",
    "Nicaragua":"Managua",
    "Niger":"Niamey",
    "Nigeria":"Abuja",
    "Niue":"Alofi",
    "Norfolk Island":"Kingston",
    "North Korea":"Pyongyang",
    "Northern Ireland":"Belfast",
    "Northern Mariana Islands":"Garapan",
    "Norway":"Oslo",
    "Oman":"Muscat",
    "Pakistan":"Islamabad",
    "Palau":"Koror",
    "Palestine":"Gaza",
    "Panama":"Panama City",
    "Papua New Guinea":"Port Moresby",
    "Paraguay":"Asunci",
    "Peru":"Lima",
    "Philippines":"Manila",
    "Pitcairn":"Adamstown",
    "Poland":"Warsaw",
    "Portugal":"Lisbon",
    "Puerto Rico":"San Juan",
    "Qatar":"Doha",
    "Reunion":"Saint-Denis",
    "Romania":"Bucharest",
    "Russia":"Moscow",
    "Rwanda":"Kigali",
    "Saint Helena":"Jamestown",
    "Saint Kitts and Nevis":"Basseterre",
    "Saint Lucia":"Castries",
    "Saint Pierre and Miquelon":"Saint-Pierre",
    "Saint Vincent and the Grenadines":"Kingstown",
    "Samoa":"Apia",
    "San Marino":"San Marino",
    "Sao Tome and Principe":"S",
    "Saudi Arabia":"Riyadh",
    "Scotland":"Edinburgh",
    "Senegal":"Dakar",
	"Serbia":"Belgrade",
    "Seychelles":"Victoria",
    "Sierra Leone":"Freetown",
    "Singapore":"Singapore",
    "Slovakia":"Bratislava",
    "Slovenia":"Ljubljana",
    "Solomon Islands":"Honiara",
    "Somalia":"Mogadishu",
    "South Africa":"Pretoria",
    "South Korea":"Seoul",
    "South Sudan":"Juba",
    "Spain":"Madrid",
    "Sudan":"Khartoum",
    "Suriname":"Paramaribo",
    "Svalbard and Jan Mayen":"Longyearbyen",
    "Swaziland":"Mbabane",
    "Sweden":"Stockholm",
    "Switzerland":"Bern",
    "Syria":"Damascus",
    "Tajikistan":"Dushanbe",
    "Tanzania":"Dodoma",
    "Thailand":"Bangkok",
    "Togo":"Lom",
    "Tokelau":"Fakaofo",
    "Tonga":"Nuku'alofa",
    "Trinidad and Tobago":"Port of Spain",
    "Tunisia":"Tunis",
    "Turkey":"Ankara",
    "Turkmenistan":"Ashgabat",
    "Turks and Caicos Islands":"Cockburn Town",
    "Tuvalu":"Funafuti",
    "Uganda":"Kampala",
    "Ukraine":"Kiev",
    "United Arab Emirates":"Abu Dhabi",
    "United Kingdom":"London",
    "United States":"Washington",
    "Uruguay":"Montevideo",
    "Uzbekistan":"Tashkent",
    "Vanuatu":"Port Vila",
    "Venezuela":"Caracas",
    "Vietnam":"Hanoi",
    "Virgin Islands, British":"Road Town",
    "Virgin Islands, U.S.":"Charlotte Amalie",
    "Wales":"Cardiff",
    "Wallis and Futuna":"Mata-Utu",
    "Western Sahara":"El-Aai",
    "Yemen":"Sana'a",
    "Yugoslavia":"Beograd",
    "Zambia":"Lusaka",
    "Zimbabwe":"Harare",
    }
conn = pwn.remote('chall.2019.redpwn.net', 6001)
print(conn.recvline())
firstQ = str(conn.recvline()).split('of')[1][1:-4]
print(firstQ)
if firstQ in states:
	print(states[firstQ])
	conn.send(states[firstQ])
elif firstQ in countries:
	print(countries[firstQ])
	conn.send(countries[firstQ])
else:
		print('not Found')
while True:
	try:
		print(conn.recvline())
		print(conn.recvline())
		line = conn.recvline()
		secondQ = str(line).split('of',1)[1][1:-4]
		print(secondQ)
		if secondQ in states:
			print(states[secondQ])
			conn.send(states[secondQ])
		elif secondQ in countries:
			print(countries[secondQ])
			conn.send(countries[secondQ])
		else:
				print(conn.recv())

	except:
		print(conn.recv())
		print(conn.recvuntil(' ',drop=True))
		f= open("guru99.txt","w+")
		f.write(conn.recvline())
		f.close()
